name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Initialize Conda
      run: |
        echo "CONDA_BIN=$CONDA/bin" >> $GITHUB_ENV
        echo "$CONDA_BIN" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        conda env create --file environment.yml

    - name: Lint with flake8
      run: |
        conda run --name forceatlas2_env flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run --name forceatlas2_env flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda run --name forceatlas2_env pytest
